package com.github.NikBenson.RoleplayBot.modules.player;

import com.github.NikBenson.RoleplayBot.configurations.ConfigurationManager;
import com.github.NikBenson.RoleplayBot.configurations.ConfigurationPaths;
import com.github.NikBenson.RoleplayBot.configurations.JSONConfigured;
import net.dv8tion.jda.api.entities.Guild;
import net.dv8tion.jda.api.entities.User;
import net.dv8tion.jda.api.events.guild.member.GuildMemberJoinEvent;
import net.dv8tion.jda.api.hooks.ListenerAdapter;
import net.dv8tion.jda.api.hooks.SubscribeEvent;
import org.jetbrains.annotations.NotNull;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

import java.io.File;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

public class PlayerManager extends ListenerAdapter implements JSONConfigured {
	private final Guild GUILD;

	private final List<PlayerEventListener> listeners = new LinkedList<>();

	Map<String, Player> players = new HashMap<>();

	public PlayerManager(Guild guild) {
		GUILD = guild;
		guild.getJDA().addEventListener(this);
	}

	public void registerEventListener(PlayerEventListener listener) {
		if(!listeners.contains(listener)) {
			listeners.add(listener);
		}
	}

	public Player getPlayerOrCreate(User user) {
		if(!players.containsKey(user.getId())) {
			Player newPlayer = new Player(user);
			players.put(user.getId(), newPlayer);

			for(PlayerEventListener listener : listeners) {
				listener.onPlayerCreate(newPlayer);
			}
		}

		return players.get(user.getId());
	}

	@SubscribeEvent
	@Override
	public void onGuildMemberJoin(GuildMemberJoinEvent event) {
		User user = event.getUser();

		if(!user.isBot()) {
			getPlayerOrCreate(user);
		}
	}

	@Override
	public JSONObject getJSON() {
		JSONArray playersJson = new JSONArray();

		for(String user : players.keySet()) {
			Player player = players.get(user);
			playersJson.add(player.getJSON());
		}

		JSONObject json = new JSONObject();

		json.put("players", playersJson);

		return json;
	}

	@Override
	public @NotNull File getConfigPath() {
		return new File(ConfigurationManager.getInstance().getAutogeneratedConfigurationRootPath(GUILD), ConfigurationPaths.Autogenerated.PLAYERS_FILE);
	}

	@Override
	public void loadFromJSON(JSONObject json) {
		JSONArray playersJson = (JSONArray) json.get("players");

		for (Object o : playersJson) {
			JSONObject currentJson = (JSONObject) o;

			String userId = (String) currentJson.get("id");
			Player currentPlayer = new Player(currentJson, GUILD.getJDA());

			players.put(userId, currentPlayer);
		}
	}
}
